resolver: lts-11.8
packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git
extra-deps:
- iwlib-0.1.0
- alsa-mixer-0.3.0
- dbus-1.2.11
- libmpd-0.9.1.0
- parsec-numbers-0.1.0
- xml-conduit-1.9.0.0
- network-3.1.1.1
- network-bsd-2.8.1.0
- socks-0.6.1
- connection-0.3.1
flags:
  xmobar:
    all_extensions: true
extra-package-dbs: []
